"""empty message

Revision ID: 267a02079b03
Revises: 52c56cd2a395
Create Date: 2016-05-09 17:29:01.040051

"""

# revision identifiers, used by Alembic.
revision = '267a02079b03'
down_revision = '52c56cd2a395'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
