"""empty message

Revision ID: 26b6c8697bb6
Revises: 4de78b393c0f
Create Date: 2016-05-03 20:57:35.058792

"""

# revision identifiers, used by Alembic.
revision = '26b6c8697bb6'
down_revision = '4de78b393c0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
