"""empty message

Revision ID: 52c56cd2a395
Revises: bfcf77d8be89
Create Date: 2016-05-05 00:22:40.056396

"""

# revision identifiers, used by Alembic.
revision = '52c56cd2a395'
down_revision = 'bfcf77d8be89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('touxiang', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'touxiang')
    ### end Alembic commands ###
